### ISSUE TITLE
Question regarding the Usage

### ISSUE THREAD

**Issue by YD-97** [BoukraichiHamza/DuelLinksBot#1]
Hi. 

Thanks for the repo. I just wonder how to use the bot. Would you please clarify?

Cheers, 
YD.

**Comment by BoukraichiHamza** [comment]
Hi,

Please note that the developpement of the bot is on standby for now, feel free to fork to make your own version.

The bot is a basic autoclicker who look for the adequate picture to click on it, you'll find the examples I used for testing in one of  the folders (Image for example). Make your own screenshots from the game using any language you want but in 1280*720 resolution.

Make you sure you have python3 and pyautogui lib installed.

Change the folder name in the line 33 in main.py to the folder containing the screenshots you made. Then launch main.py on a terminal ( conda prompt for example).

Enjoy.
